theme: jekyll-theme-leap-day

baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://js4k.github.io" # the base hostname & protocol for your site
permalink: /:title
show_downloads: true
twitter_username: js4kids
github_username:  js4k

title:
  en: Reading “JavaScript for Кids”
  ru: Читая книгу «JavaScript для детей»

description:
  en: Nick Morgan's book “JavaScript for Кids” fansite
  ru: Фансайт книги Ника Моргана «JavaScript для детей»

index:
  en:
  ru: /ru/index.html

feed:
  en: /rss.xml
  ru: /ru/rss.xml
  
view_on_github:
  en: View On GitHub
  ru: Смотреть на GitHub

nav:
  en:
    home:
      name: Home
      url: /
    about:
      name: Blog
      url: /blog
  ru:
    home:
      name: Главная
      url: /ru/
    about:
      name: Блог
      url: /ru/blog
#    samples:
#      name: Код из книги
#      url: /ru/samples
#    solutions:
#      name: Решения упражнений
#      url: /ru/solutions

language:
  en: English
  ru: Русский

site_languages:
  en: This site in other languages 
  ru: Этот сайт на других языках
page_languages:
  en: This page in other languages 
  ru: Эта страница на других языках
  
twitter_link_title:
  en: Contact us by Twitter
  ru: Пишите нам в Twitter
 
downloads:
  en: Downloads
  ru: Скачать

solutions_download:
  en:
    name: Solutions
    url: https://www.nostarch.com/download/JavaScriptForKidsSolutions.zip
  ru:
    name: Упражнения
    url: https://github.com/js4k/JavaScriptForKidsSolutionsRU/archive/v1.0.0.zip
    
code_download:
  en:
    name: Samples
    url: https://www.nostarch.com/download/JavaScriptForKidsCode.zip
  ru:
    name: Примеры
    url: https://github.com/js4k/JavaScriptForKidsCodeRU/archive/v1.0.0.zip

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
